---
# apt install chrony -y
- name: Install Chrony Ubuntu
  ansible.builtin.apt:
    name: chrony 
    state: present 
    update_cache: yes

# systemctl enable chrony --now
- name: Start chrony service ubuntu 
  ansible.builtin.systemd:
    name: chrony
    state: started
    enabled: yes 


# timedatectl set-timezone Europe/Moscow
- name: Set timezone to Europe/Moscow
  community.general.timezone:
    name: Europe/Moscow
  notify: Restart Chrony Ubuntu 



