# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/focal64"
    config.vbguest.auto_update = false
    
    config.vm.define "web01" do |web01|
        web01.vm.network "private_network", ip: "192.168.11.150"
        web01.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
      end
        web01.vm.hostname = "web01"
    end
    
    config.vm.define "files01" do |files01|
        files01.vm.network "private_network", ip: "192.168.11.160"
        files01.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 4
    end
    files01.vm.hostname = "files01"
    end
    
end