Vagrant.configure("2") do |config|
    # Define web01
    config.vm.define "web01" do |web01|
      web01.vm.box = "ubuntu/focal64"
      web01.vm.hostname = "web01"
      web01.vm.network "private_network", ip: "192.168.50.110"
      web01.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = "4"
      end
      # Ansible provisioner for web01
      web01.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.verbose = "vvv"
        ansible.compatibility_mode = "2.0"
        ansible.extra_vars = {
          ansible_user: "vagrant",
          ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"
        }
      end
    end
  
    # Define db01
    config.vm.define "db01" do |db01|
      db01.vm.box = "ubuntu/focal64"
      db01.vm.hostname = "db01"
      db01.vm.network "private_network", ip: "192.168.50.120"
      db01.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = "4"
      end
      # Ansible provisioner for db01
      db01.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.verbose = "vvv"
        ansible.compatibility_mode = "2.0"
        ansible.extra_vars = {
          ansible_user: "vagrant",
          ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"
        }
      end
    end
  
    # Define mon01
    config.vm.define "mon01" do |mon01|
      mon01.vm.box = "ubuntu/focal64"
      mon01.vm.hostname = "mon01"
      mon01.vm.network "private_network", ip: "192.168.50.130"
      mon01.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = "4"
      end
      # Ansible provisioner for mon01
      mon01.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
        ansible.verbose = "vvv"
        ansible.compatibility_mode = "2.0"
        ansible.extra_vars = {
          ansible_user: "vagrant",
          ansible_ssh_private_key_file: "~/.vagrant.d/insecure_private_key"
        }
      end
    end
  
    # SSH settings
    config.ssh.insert_key = false
    config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key"]
  end