---
- name: Install roles
  hosts: all
  become: true
  gather_facts: true 
  roles:
    - chrony
    - node_exporter

- hosts: gitlab
  become: yes
  roles:
    - gitlab


- hosts: appservers
  become: yes
  roles: 
    - git_install
    - php7.4
    - composer
    - gitlab-runner
    - repository_init
    - nginx
    - prometheus


- hosts: db
  become: yes 
  roles:
    - python 
    # - postgresql
    # - pgsql_setup
    