---
- name: Install roles
  hosts: all
  become: true
  gather_facts: true 
  roles:
    - chrony
    - node_exporter
    - filebeat

- hosts: gitlab
  become: yes
  roles:
    - gitlab


- hosts: appservers
  become: yes
  roles: 
    - git_install
    - php7.4
    - composer
    - gitlab-runner
    - repository_init
    - nginx
    


- hosts: db
  become: yes 
  roles:
    - python 
    - postgresql
    - pgsql_setup


- hosts: elk01
  become: yes
  roles:
    - elasticsearch
    - grafana
    - kibana
    - logstash
    - node_exporter
    - filebeat

- hosts: prom01
  become: yes
  roles:
    - prometheus
    - node_exporter
    - filebeat

    