Vagrant.configure("2") do |config|
    config.vm.define "app01" do |app01|
        app01.vm.box = "ubuntu/focal64"
        app01.vm.hostname = "app01"
        app01.vm.network "private_network", ip: "192.168.50.11"
        app01.vm.provider "virtualbox" do |vb|
            vb.memory = "4096"
            vb.cpus = "4"
        end
    end  # Add this end

    config.vm.define "gitlab01" do |gitlab01|
        gitlab01.vm.box = "ubuntu/focal64"
        gitlab01.vm.hostname = "gitlab01"
        gitlab01.vm.network "private_network", ip: "192.168.50.12"
        gitlab01.vm.provider "virtualbox" do |vb|
            vb.memory = "4096"
            vb.cpus = "4"
        end 
    end  # Add this end

    config.vm.define "vpn01" do |vpn01|
        vpn01.vm.box = "ubuntu/focal64"
        vpn01.vm.hostname = "vpn01"
        vpn01.vm.network "private_network", ip: "192.168.50.13"
        vpn01.vm.provider "virtualbox" do |vb|
            vb.memory = "4096"
            vb.cpus = "4"
        end 
    end

    config.vm.define "db01" do |db01|
        db01.vm.box = "ubuntu/focal64"
        db01.vm.hostname = "db01"
        db01.vm.network "private_network", ip: "192.168.50.14"
        db01.vm.provider "virtualbox" do |vb|
            vb.memory = "4096"
            vb.cpus = "4"
        end 
    end

    config.vm.define "prod01" do |prod01|
        prod01.vm.box = "ubuntu/focal64"
        prod01.vm.hostname = "prod01"
        prod01.vm.network "private_network", ip: "192.168.50.15"
        prod01.vm.provider "virtualbox" do |vb|
            vb.memory = "4096"
            vb.cpus = "4"
        end 
    end

    config.vm.define "prom01" do |prom01|
        prom01.vm.box = "ubuntu/focal64"
        prom01.vm.hostname = "prom01"
        prom01.vm.network "private_network", ip: "192.168.50.16"
        prom01.vm.provider "virtualbox" do |vb|
            vb.memory = "4096"
            vb.cpus = "4"
        end 
    end

    config.vm.define "prom01" do |elk01|
        elk01.vm.box = "ubuntu/focal64"
        elk01.vm.hostname = "elk01"
        elk01.vm.network "private_network", ip: "192.168.50.17"
        elk01.vm.provider "virtualbox" do |vb|
            vb.memory = "4096"
            vb.cpus = "4"
        end 
    end

    config.ssh.insert_key = false
    config.ssh.private_key_path = ["~/.vagrant.d/insecure_private_key", "~/.ssh/id_rsa"]
    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
end