# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/focal64"
      config.vbguest.auto_update = false
    
      config.vm.define "server-elk01" do |serverelk01|
          serverelk01.vm.network "private_network", ip: "10.0.0.70"
          serverelk01.vm.provider "virtualbox" do |v|
          v.memory = 2048
          v.cpus = 2
        end
        serverelk01.vm.hostname = "serverelk01"
      end
    
      config.vm.define "kafka" do |kafka|
          kafka.vm.network "private_network", ip: "10.0.0.60"
          kafka.vm.provider "virtualbox" do |v|
          v.memory = 4096
          v.cpus = 4
        end
        kafka.vm.hostname = "kafka"
      end
  
      config.vm.define "vpn01" do |vpn01|
          vpn01.vm.network "private_network", ip: "10.0.0.80"
          vpn01.vm.provider "virtualbox" do |v|
            v.memory = 2048
            v.cpus = 2
          end
          vpn01.vm.hostname = "vpn01"
      end
  
      config.vm.define "db01" do |db01|
          db01.vm.network "private_network", ip: "10.0.0.90"
          db01.vm.provider "virtualbox" do |v|
            v.memory = 2048
            v.cpus = 2
          end
          db01.vm.hostname = "db01"
      end
    
    end