Vagrant.configure("2") do |config|

    # Конфигурация первой виртуальной машины
    config.vm.define "vm1" do |vm1|
      vm1.vm.box = "ubuntu/focal64"
      vm1.vm.network "private_network", type: "static", ip: "192.168.50.10"
      vm1.vm.network "forwarded_port", guest: 80, host: 8081
      vm1.vm.hostname = "web01"
    end
  
    # Конфигурация второй виртуальной машины
    config.vm.define "vm2" do |vm2|
      vm2.vm.box = "ubuntu/focal64"
      vm2.vm.network "private_network", type: "static", ip: "192.168.50.11"
      vm2.vm.hostname = "files01"
    end
    
  end
  
  