# -*- mode: ruby -*-
# vi: set ft=ruby :
ENV['VAGRANT_EXPERIMENTAL'] = "disks"

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
      config.vbguest.auto_update = false
    
      config.vm.define "pxesrv" do |pxesrv|
        pxesrv.vm.network "private_network", ip: "192.168.11.150"
        pxesrv.vm.provider "virtualbox" do |v|
          v.memory = 2048
          v.cpus = 2
        end
        pxesrv.vm.hostname = "pxesrv"
      end

end