# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/focal64"
    config.vbguest.auto_update = false
  
    config.vm.define "web01" do |web01|
        web01.vm.network "private_network", ip: "192.168.11.150"
        web01.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
      end
        web01.vm.hostname = "web01"
    end
  
    config.vm.define "db01" do |db01|
        db01.vm.network "private_network", ip: "192.168.11.160"
        db01.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 4
      end
       db01.vm.hostname = "db01"
      #config.vm.provision "shell", path: "./scripts/gitlab.sh"
    end

    config.vm.define "mon01" do |mon01|
        mon01.vm.network "private_network", ip: "192.168.11.170"
        mon01.vm.provider "virtualbox" do |v|
          v.memory = 2048
          v.cpus = 2
        end
          mon01.vm.hostname = "mon01"
    end
  end

  