# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/focal64"
      config.vbguest.auto_update = false
    
      config.vm.define "app01" do |app01|
          app01.vm.network "private_network", ip: "192.168.11.150"
          app01.vm.provider "virtualbox" do |v|
          v.memory = 2048
          v.cpus = 2
        end
        app01.vm.hostname = "app01"
      end
    
      config.vm.define "gitlab" do |gitlab|
          gitlab.vm.network "private_network", ip: "192.168.11.160"
          gitlab.vm.provider "virtualbox" do |v|
          v.memory = 4096
          v.cpus = 4
        end
          gitlab.vm.hostname = "gitlab"
      end
      
      config.vm.define "vpn01" do |vpn01|
        vpn01.vm.network "private_network", ip: "192.168.11.170"
        vpn01.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 4
      end
        vpn01.vm.hostname = "vpn01"
    end
  
      config.vm.define "db01" do |db01|
          db01.vm.network "private_network", ip: "192.168.11.180"
          db01.vm.provider "virtualbox" do |v|
          v.memory = 2048
          v.cpus = 2
          end
          db01.vm.hostname = "db01"
      end
    end
  
    