Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/focal64"
      config.vbguest.auto_update = false
    
      config.vm.define "app" do |app|
          app.vm.network "private_network", ip: "192.168.11.150"
          app.vm.provider "virtualbox" do |v|
          v.memory = 2048
          v.cpus = 2
      end
        app.vm.hostname = "app"
    end
end