$global = <<SCRIPT

sudo apt update -y
sudo apt install sshpass -y
sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
sudo sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/' /etc/ssh/sshd_config
yes y | ssh-keygen -f /home/vagrant/.ssh/id_rsa -t rsa -N ''

cat > ~/.ssh/config <<EOF
Host ansible
   StrictHostKeyChecking no
   UserKnownHostsFile=/dev/null

Host files01
   StrictHostKeyChecking no
   UserKnownHostsFile=/dev/null

Host web01
   StrictHostKeyChecking no
   UserKnownHostsFile=/dev/null
EOF

sudo tee -a /etc/hosts > /dev/null <<EOF
192.168.10.11 ansible
192.168.10.12 files01
192.168.10.13 web01
EOF

if [ "$HOSTNAME" = "ansible" ]; then
  sudo apt install ansible python3-pip -y
  pip3 install ansible --upgrade
  ansible-galaxy collection install community.docker
  ansible-galaxy collection install ansible.posix
fi

sudo chmod 0600 /home/vagrant/.ssh/config
sudo systemctl restart sshd

SCRIPT

$ssh = <<SCRIPT1
declare -a hosts=("ansible" "files01" "web01")

for host in "${hosts[@]}"
do
    # Пропускаем curent host
    if [ "$HOSTNAME" = "$host" ]; then
        continue
    fi
    sshpass -p vagrant ssh-copy-id "$host"
done

for host in "${hosts[@]}"
do
    # Пропускаем curent host
    if [ "$HOSTNAME" = "$host" ]; then
        continue
    fi
    sshpass -p vagrant ssh "$host" 'cat .ssh/id_rsa.pub' >> /home/vagrant/host-ids.pub
done

for host in "${hosts[@]}"
do
    # Пропускаем curent host
    if [ "$HOSTNAME" = "$host" ]; then
        continue
    fi
    sshpass -p vagrant ssh-copy-id -f -i /home/vagrant/host-ids.pub "$host"
done

SCRIPT1

Vagrant.configure("2") do |config|

  config.vm.provision "shell", privileged: false, inline: $global

  machines = [
    { name: "ansible", ip_suffix: "11" },
    { name: "files01", ip_suffix: "12" },
    { name: "web01", ip_suffix: "13" }
  ]

  machines.each do |machine|
    config.vm.define machine[:name] do |node|
      node.vm.box = "ubuntu/focal64"
      node.vm.hostname = machine[:name]
      ip = "192.168.10.#{machine[:ip_suffix]}"
      node.vm.network "private_network", ip: ip

      node.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "1024"
      end

	    if machine[:name] == "web01"
	    node.vm.network "forwarded_port", guest: 80, host: 8000
	    end
	  
    end 
  end

  if ENV['RUN_SSH_PROVISION'] == 'true'
    config.vm.provision "ssh", type: "shell", privileged: false, inline: $ssh
  end

end
