stages:
  - docker_build
  - docker_push


Build docker image:
  stage: docker_build
  when: manual 
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t "$DOCKER_IMAGE_NAME" ./devops_task_normal_three/app 

Push to registry:
  stage: docker_push
  when: manual 
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
  script:
    - docker push "$DOCKER_IMAGE_NAME"