---
- name: Nginx | Install Nginx
  ansible.builtin.apt:
    name: nginx 
    state: present
    update_cache: true

- name: Nginx | delete folder
  ansible.builtin.file: 
    path: /var/www/html
    state: absent 


- name: Nginx | Copy our landing to folder 
  ansible.builtin.copy:
    src: file/html
    dest: /var/www/
    owner: vagrant
    group: vagrant 
    mode: 0644
