{
 "title": "Docker and OS Metrics",
 "description": "Dashboard with details of the container and host OS metrics",
 "tags": [
  "prometheus",
  "cAdvisor",
  "node-exporter"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "60s" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Time during which server is in operation",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "description": "Total containers running",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (name) (rate(container_tasks_state{image!=\"\", state=~\"running\"}[$__range])))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / (node_memory_SwapTotal_bytes )) * 100"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "description": "The number (after merges) of I/O requests completed per second for the device",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total[$__range])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "- rate(node_disk_writes_completed_total[$__range])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "max(rate(container_network_transmit_bytes_total{name!=\"\"}[$__range])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "max(rate(container_network_transmit_bytes_total{name!=\"\"}[$__range])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RSS Memory Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name!=\"\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[$__range])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Used Memory per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}