---
- name: Install python 
  ansible.builtin.apt:
    name: python3 
    state: present 

- name: Install python-pip3
  ansible.builtin.apt:
    name: python3-pip 
    state: present

- name: Install required Python libraries
  ansible.builtin.pip:
    name: psycopg2-binary
    state: present 