---
# Установка docker&docker-compose
docker_install: false # нужно ли устанавливать docker

# Установка pip3 и пакетов docker и docker-compose
docker_pip3_install: false
docker_pip3_docker_version: "6.1.3"
docker_pip3_docker_compose_version: "1.29.2"

# Останавливаем/удаляем docker-compose
docker_compose_stop: false
docker_compose_stop_directory_destination_path: ""
docker_compose_stop_project_name: ""
docker_compose_remove: false
docker_compose_remove_destination_path: ""

# Создаем директорию и шаблон для docker-compose
docker_compose_template: false
docker_compose_directory_path: "/home/ansible"
docker_compose_directory_mode: "0755"
docker_compose_directory_group: "root"
docker_compose_directory_owner: "root"
docker_compose_template_path: "{{ role_path }}/templates/docker-compose.yml.j2" # путь до шаблона docker-compose
docker_compose_template_destination_path: "" # путь до docker-compose на хосте
docker_compose_template_owner: "root"
docker_compose_template_group: "root"
docker_compose_template_mode: '0644'
docker_compose_template_backup: yes

# Прокидываение файла для его использования docker-composом
docker_compose_env_file: false
docker_compose_env_file_src: "{{ role_path }}/files/app.env"
docker_compose_env_file_dest: ""
docker_compose_env_file_mode: "0644"
docker_compose_env_file_group: "root"
docker_compose_env_file_owner: "root"

# Cтарт docker-compose
docker_compose_start: false # нужно ли прокинуть и запустить docker-compose
docker_compose_start_directory_destination_path: "" # путь до директории с docker-compose
docker_compose_start_project_name: "default"

# Добавление пользователей
docker_add_user_to_docker_group: false # нужно ли добавлять пользователей в docker group
docker_users: # список пользователей, которых нужно добавить в docker group
  - ansible

# Прокидываем файл с зеркалами
docker_change_registry_mirrors: false
docker_registry_mirrors_template_path: "{{ role_path }}/templates/mirrors/daemon.json.j2"
docker_registry_mirrors_destination_path: "/etc/docker/daemon.json"
docker_registry_mirrors_owner: "root"
docker_registry_mirrors_group: "root"
docker_registry_mirrors_mode: "0600"
docker_registry_mirrors_backup: yes
docker_registry_mirrors:
  - "https://mirror.gcr.io"
  - "https://daocloud.io"
  - "https://c.163.com/"
  - "https://registry.docker-cn.com"

# Docker restart
docker_restart_handler_state: "restarted"
docker_restart_ignore_errors: "true"
