# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/focal64"
    config.vbguest.auto_update = false
  
    config.vm.define "game01" do |game01|
      game01.vm.network "private_network", ip: "192.168.11.150"
      game01.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
      game01.vm.hostname = "game01"
  end
end
