---
- name: Postgres
  hosts: "all"
  become: true 
  tasks:
    - name: Install base tools
      dnf:
        name:
          - vim
          - telnet 
        state: present
        update_cache: true  


- name: install postgres 14 
  hosts: "all"
  become: true 
  roles: 
  - install_postgers
