gitlab_runner_download_url: https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
gitlab_runner_bin_path: /usr/local/bin/gitlab-runner
gitlab_runner_user: gitlab-runner
gitlab_runner_working_dir: /home/gitlab-runner
gitlab_runner_service_file: /etc/systemd/system/gitlab-runner.service
